<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Procurement.UI</RootNamespace>
    <AssemblyName>Procurement.UI</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppConfig>App.config</AppConfig>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Procurement.Core\Procurement.Core.csproj" />
    <ProjectReference Include="..\Procurement.Data\Procurement.Data.csproj" />
    <ProjectReference Include="..\Procurement.Erp\Procurement.Erp.csproj" />
    <ProjectReference Include="..\Procurement.Engine\Procurement.Engine.csproj" />
    <ProjectReference Include="..\Procurement.Suppliers.DigiKey\Procurement.Suppliers.DigiKey.csproj" />
    <ProjectReference Include="..\Procurement.Suppliers.Farnell\Procurement.Suppliers.Farnell.csproj" />
  </ItemGroup>

</Project>
