using System.Collections.Generic;

namespace Procurement.Core.Models
{
    /// <summary>
    /// Input to IErpConnector.CreatePurchaseOrderAsync. One PO per supplier (spec correction, aug
    /// 2026) — lines here can originate from different PurchaseRequests as long as they share
    /// SupplierCode; grouping-by-supplier happens in ProcurementEngine.PlaceOrdersAsync before this
    /// draft is built.
    /// </summary>
    public class PurchaseOrderDraft
    {
        public string SupplierCode { get; set; }
        public string Currency { get; set; }

        /// <summary>Generated by the caller (spec §10 format) before the ERP PO exists, so it's set on the PurchaseOrder row right away — see PurchaseOrder.IdempotencyKey.</summary>
        public string IdempotencyKey { get; set; }

        public List<PurchaseOrderDraftLine> Lines { get; set; } = new List<PurchaseOrderDraftLine>();
    }

    public class PurchaseOrderDraftLine
    {
        public int PurchaseRequestLineId { get; set; }
        public string SupplierPartNumber { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal LineTotal { get; set; }
    }
}
